service: dove-auth

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: prod
  deploymentBucket:
    name: dove-serverless-deploy
  environment:
    DYNAMODB_TABLE: dove-auth-codes
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - sns:Publish
        - ses:SendEmail
      Resource:
        - arn:aws:dynamodb:eu-central-1:704428061275:table/dove-auth-codes
        - arn:aws:ses:eu-central-1:704428061275:identity/dove.no.reply@gmail.com
        - "*"
       

  httpApi:
    cors: 
      allowedOrigins:
        - http://localhost:5173
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - POST
        - OPTIONS
        - GET

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

